# Generated by Django 4.2.17 on 2025-01-03 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wing_type",
                    models.CharField(
                        choices=[
                            ("TB2", "Tb2"),
                            ("TB3", "Tb3"),
                            ("AKINCI", "Akinci"),
                            ("KIZILELMA", "Kizilelma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
