# Generated by Django 4.2.17 on 2025-01-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_tail_fuselage_avionics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avionics",
            options={
                "permissions": [
                    ("create_avionics", "Can create avionics"),
                    ("view_create_avionics_page", "Can view create avionics page"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="fuselage",
            options={
                "permissions": [
                    ("create_fuselage", "Can create a fuselage"),
                    ("view_create_fuselage_page", "Can view create fuselage page"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="tail",
            options={
                "permissions": [
                    ("create_tail", "Can create a tail"),
                    ("view_create_tail_page", "Can view create tail page"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="wing",
            options={
                "permissions": [
                    ("create_wing", "Can create a wing"),
                    ("view_create_wing_page", "Can view create wing page"),
                ]
            },
        ),
    ]
