# Generated by Django 4.2.17 on 2025-01-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_aircraft"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsedWing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft_type", models.CharField(max_length=20)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_wings",
                        to="main.aircraft",
                    ),
                ),
                (
                    "wing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_by_aircraft",
                        to="main.wing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsedTail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft_type", models.CharField(max_length=20)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_tails",
                        to="main.aircraft",
                    ),
                ),
                (
                    "tail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_by_aircraft",
                        to="main.tail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsedFuselage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft_type", models.CharField(max_length=20)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_fuselages",
                        to="main.aircraft",
                    ),
                ),
                (
                    "fuselage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_by_aircraft",
                        to="main.fuselage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsedAvionics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft_type", models.CharField(max_length=20)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_avionics",
                        to="main.aircraft",
                    ),
                ),
                (
                    "avionics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_by_aircraft",
                        to="main.avionics",
                    ),
                ),
            ],
        ),
    ]
